ALTER TABLE clients ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;
ALTER TABLE suppliers ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;
ALTER TABLE products ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;
